### ISSUE TITLE
Create JSON file for communities list

### ISSUE THREAD

**Issue by felicianotech** [felicianotech/discourse.directory#5]

**Comment by virenb** [comment]
I will work on this.

**Comment by felicianotech** [comment]
Let me know if you have any questions. :smile:

**Comment by virenb** [comment]
Hi @felicianotech, sorry, still a little new to this. I forked the repository and then added the .json file and did a pull request. Could you have a look?

**Comment by felicianotech** [comment]
You didn't open a pull request on this project.

**Comment by felicianotech** [comment]
Implemented in #24.
